### ISSUE TITLE
Cancel Build button click is not working 

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#141] opened 2018-05-13 14:21 UTC
No action or appropriate message is shown after clicking "Cancel build" button of test collection build screen.

Steps to reproduce:
1. create a collection with any project repositories.
2. click build button
3. if test build fails, you can see test collection at float right location of window.
4. if we open test build window and click "cancel build" button then nothing happens. i.e. no appropriate message or action is executed.

Expected result: Cancel functionality should be implemented with appropriate error message if there is some issue while cancel build.

**Comment by nguyenLisa** [comment] 2018-05-13 19:29
This seems to be a duplicate of closed issue #21 . Could you verify if this is indeed the same bug? In that case, please close this one and re-open #21 .

**Closed as completed** 2018-05-14 23:23 UTC
Labels: bug, medium
