### ISSUE TITLE
Second Collection also shows list of First collection items

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm#103] opened 2018-04-19 17:00 UTC
Search for java projects, and select 2 of them and create a new collection. Now search for android projects and select 3 of them and create another collection. Now we see that even the previous java projects which were added for the first collection are added in the second collection.(in total 5 projects in the second collection).

**Comment by johannesduesing** [comment] 2018-05-21 14:41
I could not reproduce this bug. I'm assuming you might have forgotten to remove the java projects from the list of selected projects when creating the android collection. By default, the projects added in the last collection will stay in the list of selected projects for the next creation. I think this is intended behavior.

**Comment by nguyenLisa** [comment] 2018-10-02 06:27
Closing.

**Closed by nguyenLisa** 2018-10-02 06:27 UTC
Labels: bug
